@startuml

title __SUPPORT's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace parser.support {
          class org.concordion.internal.parser.support.Attribute {
              + name : String
              + value : String
              + Attribute()
              + toString()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace parser.support {
          class org.concordion.internal.parser.support.ConciseExpressionParser {
              {static} - COMMAND_VALUE_PATTERN : Pattern
              - namespaces : Map<String, String>
              - sourcePrefix : String
              - targetPrefix : String
              + ConciseExpressionParser()
              + ConciseExpressionParser()
              + isExecuteCommand()
              + parse()
              + parse()
              + parseCommandValueAndAttributes()
              + parseCommandValueAndAttributes()
              - createStatementFromNamespacePrefix()
              - parseStatement()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace parser.support {
          class org.concordion.internal.parser.support.ConcordionStatement {
              + attributes : List<Attribute>
              + command : Attribute
              + text : String
              + ConcordionStatement()
              + withAttribute()
              + withText()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace parser.support {
          class org.concordion.internal.parser.support.ConcordionSyntaxException {
              {static} - serialVersionUID : long
              + ConcordionSyntaxException()
              + ConcordionSyntaxException()
              + ConcordionSyntaxException()
              + ConcordionSyntaxException()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
