@startuml

title __RUNNER's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.CachedResultsUnitTest {
              {static} + EXAMPLE_1_NAME : String
              {static} + EXAMPLE_2_NAME : String
              - runResults : RunResultsCache
              + before()
              + testCacheInProgress()
              + testCacheInProgressWithExample()
              + testNotFoundInCache()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.CachedResultsUnitTest.JustAnotherClass {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.DefaultConcordionRunnerTest {
              + systemErrRule : SystemErrRule
              + doesNotLogAssertionErrors()
              + doesNotLogAssertionErrorsWhenExpectedToFailEither()
              + doesNotLogAssertionErrorsWhenUnimplementedEither()
              + doesNotThrowExceptionOnAssertionErrorWhenExpectedToPass()
              + logsExceptions()
              + returnsFailureOnJUnitFailure()
              + returnsIgnoredOnJUnitSuccessWhenExpectedToFail()
              + returnsIgnoredOnJUnitSuccessWhenIgnoredCountGreaterThanZero()
              + returnsIgnoredOnJUnitSuccessWhenUnimplemented()
              + returnsSuccessOnJUnitSuccess()
              + throwsAssertionErrorOnJUnitFailureWhenExpectedToFail()
              + throwsAssertionErrorOnJUnitFailureWhenUnimplemented()
              + throwsExceptionOnCheckedException()
              + throwsRuntimeExceptionOnRuntimeException()
              + throwsWrappedExceptionOnThrowable()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.DefaultConcordionRunnerTest.ExpectedToFailClass {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.DefaultConcordionRunnerTest.TestDefaultConcordionRunner {
              # decodeJUnitResult()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.DefaultConcordionRunnerTest.UnannotatedClass {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.DefaultConcordionRunnerTest.UnimplementedClass {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace runner {
          class org.concordion.internal.runner.StubResult {
              {static} + FAILURE : StubResult
              {static} + SUCCESS : StubResult
              - failures : List<Failure>
              - ignoreCount : int
              {static} - serialVersionUID : long
              + getFailures()
              + getIgnoreCount()
              + wasSuccessful()
              + withFailure()
              + withIgnoreCount()
          }
        }
      }
    }
  }
  

  org.concordion.internal.runner.CachedResultsUnitTest +-down- org.concordion.internal.runner.CachedResultsUnitTest.JustAnotherClass
  org.concordion.internal.runner.DefaultConcordionRunnerTest o-- org.concordion.internal.runner.DefaultConcordionRunnerTest.TestDefaultConcordionRunner : runner
  org.concordion.internal.runner.DefaultConcordionRunnerTest +-down- org.concordion.internal.runner.DefaultConcordionRunnerTest.ExpectedToFailClass
  org.concordion.internal.runner.DefaultConcordionRunnerTest +-down- org.concordion.internal.runner.DefaultConcordionRunnerTest.TestDefaultConcordionRunner
  org.concordion.internal.runner.DefaultConcordionRunnerTest +-down- org.concordion.internal.runner.DefaultConcordionRunnerTest.UnannotatedClass
  org.concordion.internal.runner.DefaultConcordionRunnerTest +-down- org.concordion.internal.runner.DefaultConcordionRunnerTest.UnimplementedClass


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
