@startuml

title __WHITESPACE's Class Diagram__\n

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace assertEquals {
          namespace whitespace {
            class spec.concordion.common.command.assertEquals.whitespace.LineContinuationsTest {
                - snippets : List<String>
                + addSnippet()
                + processSnippets()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace assertEquals {
          namespace whitespace {
            class spec.concordion.common.command.assertEquals.whitespace.LineContinuationsTest.Result {
                + failures : String
                + successes : String
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace assertEquals {
          namespace whitespace {
            class spec.concordion.common.command.assertEquals.whitespace.NormalizationTest {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace assertEquals {
          namespace whitespace {
            class spec.concordion.common.command.assertEquals.whitespace.WhitespaceTest {
                + normalize()
                + whichSnippetsFail()
                + whichSnippetsSucceed()
                - fails()
                {static} - replaceNamedWhitespaceWithRealWhitespaceCharacters()
                {static} - replaceRealWhitespaceCharactersWithNames()
                - succeeds()
                {static} - which()
            }
          }
        }
      }
    }
  }
  

  spec.concordion.common.command.assertEquals.whitespace.LineContinuationsTest +-down- spec.concordion.common.command.assertEquals.whitespace.LineContinuationsTest.Result


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
