@startuml

title __EXTENSION's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace extension {
          class org.concordion.internal.extension.ExtensionChecker {
              {static} - EMBED_EXTENSION_CLASS : String
              {static} - EXCEL_EXTENSION_CLASS : String
              {static} - EXECUTE_ONLY_IF_EXTENSION_CLASS : String
              {static} - OUTDATED_EXCEL_EXTENSION_CLASS : String
              {static} - OUTDATED_EXTENSIONS_CLASS : String
              {static} - OUTDATED_MARKDOWN_EXTENSION_CLASS : String
              {static} - RUN_TOTALS_EXTENSION_CLASS : String
              {static} - SCREENSHOT_EXTENSION_CLASS : String
              {static} - checked : boolean
              {static} + checkForOutdatedExtensions()
              {static} - checkExtensionCompatibility()
              {static} - failIfIncompatible()
              {static} - failIfOutdatedExtensionFound()
              {static} - failIfPresent()
              {static} - isCompatible()
              {static} - warnIfIncompatible()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace extension {
          class org.concordion.internal.extension.ExtensionInitialisationException {
              {static} - serialVersionUID : long
              + ExtensionInitialisationException()
              + ExtensionInitialisationException()
              + ExtensionInitialisationException()
              + ExtensionInitialisationException()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace extension {
          class org.concordion.internal.extension.FixtureExtensionLoader {
              + addExtensions()
              + getExtensionsForFixture()
              - getExtensionField()
              - getExtensionsFromAnnotatedFields()
              - getExtensionsFromClassAnnotation()
              - newInstance()
              - validateNonNull()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
