@startuml

title __LISTENER's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace listener {
          class org.concordion.internal.listener.BreadcrumbRendererTest {
              + systemErrRule : SystemErrRule
              {static} - BAD_PACKAGE_RESOURCE_NAME : String
              {static} - BAD_SPEC_RESOURCE_NAME : String
              {static} - ERRONEOUS_HTML : String
              {static} - EXPECTED_SOURCE_NAME : String
              {static} - GOOD_HTML : String
              {static} - PACKAGE_RESOURCE_NAME : String
              {static} - SPEC_RESOURCE_NAME : String
              - renderer : BreadcrumbRenderer
              - stubSource : StubSource
              + BreadcrumbRendererTest()
              + cachesResult()
              + createsBodyIfNoneExists()
              + createsSpanWithParentBreadcrumb()
              + logsNameOfErroneousHtmlFileOnParseError()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace listener {
          class org.concordion.internal.listener.DocumentStructureImproverTest {
              - document : Document
              - html : Element
              - improver : DocumentStructureImprover
              + testAddsHeadIfMissing()
              + testTransfersEverythingBeforeBodyIntoNewlyCreatedHead()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace listener {
          class org.concordion.internal.listener.JavaScriptLinkerTest {
              {static} - NOT_NEEDED_PARAMETER : Resource
              + xmlOutputContainsAnExplicitEndTagForScriptElement()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace listener {
          class org.concordion.internal.listener.MetadataCreatorTest {
              - document : Document
              - head : Element
              - html : Element
              - metadataCreator : MetadataCreator
              + MetadataCreatorTest()
              + testAddsContentTypeMetadataIfMissing()
              + testDoesNotAddContentTypeMetadataIfAlreadyPresent()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
