@startuml

title __SCOPEDOBJECTS's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace scopedObjects {
          class org.concordion.internal.scopedObjects.InvalidScopedObjectTest {
              ~ x : Integer
              + before()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace scopedObjects {
          class org.concordion.internal.scopedObjects.ScopedFieldsTest {
              ~ exampleInteger : ScopedObjectHolder<AtomicInteger>
              ~ specificationInteger : ScopedObjectHolder<AtomicInteger>
              {static} - firstRun : boolean
              {static} - integer : int
              + before()
              + runTest()
              + test1()
              + test2()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace scopedObjects {
          class org.concordion.internal.scopedObjects.ScopedObjectFactoryTest {
              - nonStaticValue : int
              - scopedValue : ScopedObject
              {static} - staticValue : int
              + before()
              + test1()
              + test2()
              - testIntegerValues()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace scopedObjects {
          class org.concordion.internal.scopedObjects.ScopedObjectRepositoryKeyTest {
              + testEqualsSpecScope()
              - checkEqualsHashCode()
              - checkNotEqualsNotHashCode()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
