@startuml

title __STRATEGIES's Class Diagram__\n

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace verifyRows {
          namespace strategies {
            class spec.concordion.common.command.verifyRows.strategies.BaseMatchStrategyTest {
                + users : List<MultiValueResult>
                {static} - ROWS_PLACEHOLDER : String
                + processFragment()
                + processRows()
                - parse()
                - parseSingle()
                - unwrapRows()
                - wrapRows()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace verifyRows {
          namespace strategies {
            class spec.concordion.common.command.verifyRows.strategies.BestMatchStrategyTest {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace verifyRows {
          namespace strategies {
            class spec.concordion.common.command.verifyRows.strategies.DefaultMatchStrategyTest {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace verifyRows {
          namespace strategies {
            class spec.concordion.common.command.verifyRows.strategies.KeyMatchStrategyTest {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace verifyRows {
          namespace strategies {
            class spec.concordion.common.command.verifyRows.strategies.StrategiesTest {
                + processTableFragment()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace verifyRows {
          namespace strategies {
            class spec.concordion.common.command.verifyRows.strategies.UnspecifiedMatchStrategyTest {
            }
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
