@startuml

title __MODIFICATIONSTRATEGIES's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace command {
          namespace executeCommand {
            namespace modificationStrategies {
              class org.concordion.internal.command.executeCommand.modificationStrategies.ExecuteCommandListModification {
                  {static} - LEVEL_VARIABLE : String
                  + performModification()
                  - getLevel()
              }
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace command {
          namespace executeCommand {
            namespace modificationStrategies {
              abstract class org.concordion.internal.command.executeCommand.modificationStrategies.ExecuteCommandModification {
                  {abstract} + performModification()
                  # duplicateCommandForDifferentElement()
              }
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace internal {
        namespace command {
          namespace executeCommand {
            namespace modificationStrategies {
              class org.concordion.internal.command.executeCommand.modificationStrategies.ExecuteCommandTableModification {
                  + performModification()
                  - populateCommandCallByColumnMap()
              }
            }
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
