@startuml

title __EXECUTE's Class Diagram__\n

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.AccessToLinkHrefTest {
              + fragmentSucceeds()
              + myMethod()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.ContinueAfterExceptionsFixture {
              - myMethodWasCalled : boolean
              + myExceptionThrower()
              + myMethod()
              + myMethodWasCalledProcessing()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.ExecuteTest {
              - argument : String
              - myMethodWasCalled : boolean
              + getArgument()
              + myMethod()
              + myMethod()
              + myMethod()
              + myMethod()
              + myMethodWasCalledProcessing()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.ExecutingListTest {
              - treeEntries : List<MultiValueResult>
              + getNodes()
              + parseNode()
              + process()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.ExecutingTablesTest {
              + generateUsername()
              + process()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.ExecutingTablesTest.Result {
              + exceptionCount : long
              + failureCount : long
              + lastActualValue : Object
              + lastExpectedValue : String
              + successCount : long
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.FailFastFixture {
              - myMethodWasCalled : boolean
              + myExceptionThrower()
              + myMethod()
              + myMethodWasCalledProcessing()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.FailFastOnSpecificExceptionsFixture {
              - myMethodWasCalled : boolean
              + myFileNotFoundExceptionThrower()
              + myMethod()
              + myMethodWasCalledProcessing()
              + myTimeoutExceptionThrower()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace pec.concordion {
      namespace common.command {
        namespace execute {
          class spec.concordion.common.command.execute.FailFastPassthroughFixture {
          }
        }
      }
    }
  }
  

  spec.concordion.common.command.execute.ExecutingTablesTest +-down- spec.concordion.common.command.execute.ExecutingTablesTest.Result


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
