@startuml

title __JUNIT4's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace integration {
        namespace junit4 {
          class org.concordion.integration.junit4.ConcordionFrameworkMethod {
              {static} - CONCORDION_METHOD : Method
              - exampleName : String
              - notifier : RunNotifier
              + ConcordionFrameworkMethod()
              + equals()
              + getExampleName()
              + getNotifier()
              + hashCode()
              + invokeExplosively()
              + method()
              + setNotifier()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace integration {
        namespace junit4 {
          interface org.concordion.integration.junit4.ConcordionFrameworkMethod.ConcordionRunnerInterface {
              {abstract} + invoke()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace integration {
        namespace junit4 {
          class org.concordion.integration.junit4.ConcordionRunner {
              + concordionRunnerInterface : ConcordionRunnerInterface
              - concordion : Concordion
              - concordionFrameworkMethods : List<ConcordionFrameworkMethod>
              - failFastException : FailFastException
              - firstTest : boolean
              - fixtureClass : Class<?>
              - fixtureRunner : FixtureRunner
              - runResultsCache : RunResultsCache
              - setupFixture : Fixture
              {static} - suiteDepth : AtomicInteger
              + ConcordionRunner()
              + run()
              # createFixture()
              # createTest()
              # describeChild()
              # getChildren()
              # getSpecificationLocator()
              # runChild()
              # validateInstanceMethods()
              ~ invoke()
              - verifyUniqueExampleMethods()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace integration {
        namespace junit4 {
          class org.concordion.integration.junit4.JUnit4FrameworkProvider {
              + isConcordionFixture()
          }
        }
      }
    }
  }
  

  org.concordion.integration.junit4.ConcordionFrameworkMethod o-- org.concordion.integration.junit4.ConcordionFrameworkMethod.ConcordionRunnerInterface : runner
  org.concordion.integration.junit4.ConcordionFrameworkMethod +-down- org.concordion.integration.junit4.ConcordionFrameworkMethod.ConcordionRunnerInterface
  org.concordion.integration.junit4.JUnit4FrameworkProvider .up.|> TestFrameworkProvider


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
