@startuml

title __EXTENSION's Class Diagram__\n

  namespace  {
    namespace rg.concordion {
      namespace api {
        namespace extension {
          interface org.concordion.api.extension.ConcordionExtender {
              {abstract} + withAssertEqualsListener()
              {abstract} + withAssertFalseListener()
              {abstract} + withAssertTrueListener()
              {abstract} + withBreadcrumbRenderer()
              {abstract} + withBuildListener()
              {abstract} + withCommand()
              {abstract} + withDocumentParsingListener()
              {abstract} + withEmbeddedCSS()
              {abstract} + withEmbeddedCSS()
              {abstract} + withEmbeddedJavaScript()
              {abstract} + withExampleListener()
              {abstract} + withExecuteListener()
              {abstract} + withImplementationStatusModifier()
              {abstract} + withLinkedCSS()
              {abstract} + withLinkedJavaScript()
              {abstract} + withOuterExampleListener()
              {abstract} + withResource()
              {abstract} + withRunListener()
              {abstract} + withRunStrategy()
              {abstract} + withSetListener()
              {abstract} + withSource()
              {abstract} + withSpecificationLocator()
              {abstract} + withSpecificationProcessingListener()
              {abstract} + withSpecificationType()
              {abstract} + withTarget()
              {abstract} + withThrowableListener()
              {abstract} + withVerifyRowsListener()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace api {
        namespace extension {
          interface org.concordion.api.extension.ConcordionExtension {
              {abstract} + addTo()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace api {
        namespace extension {
          interface org.concordion.api.extension.ConcordionExtensionFactory {
              {abstract} + createExtension()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace api {
        namespace extension {
          interface org.concordion.api.extension.Extension {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace rg.concordion {
      namespace api {
        namespace extension {
          interface org.concordion.api.extension.Extensions {
              {abstract} + value()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
